name: Node.js Package

on:
  workflow_dispatch:
    inputs:
      NAME:
        description: Name of folder
        default: docker
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create docker folder
        run: mkdir ${{ github.event.inputs.NAME }}
      - name: Create Dockerfile
        run: |
          echo "FROM node:12.18.3-alpine" >> docker/Dockerfile
          echo "WORKDIR /app" >> docker/Dockerfile
          echo "COPY package*.json ./" >> docker/Dockerfile
          echo "RUN npm install" >> docker/Dockerfile
          echo "COPY . ." >> docker/Dockerfile
          echo "EXPOSE 3000" >> docker/Dockerfile
          echo "CMD [\"npm\", \"start\"]" >> docker/Dockerfile
          