name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job1:
          - env:
              JOB_NAME: job1
        job2:
          - env:
              JOB_NAME: job2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print job name
      run: | 
        echo "Job name: ${{ matrix.job1.env.JOB_NAME }}"

    - name: Build
      run: |
        echo "Building $JOB_NAME"
