name: CI/CD

on: 
  workflow_dispatch:
    inputs:
      ENVIRONMENT_NAME:
        description: Name of environement
        required: true

jobs:
  example_matrix:
    strategy:
      matrix:
        ${{fromJson(test.yml)}}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}