name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_cases: [api_1, api_2]
        include:
        - test_cases: api_1
          test: 1
        - test_cases: api_2
          test: 2
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: "PHP Unit test - ${{ matrix.test_cases }}"
      run: | 
         echo "${{ matrix.test_cases }} va avec ${{ matrix.test }}"